Lmod has detected the following error: These module(s) or extension(s) exist
but cannot be loaded as requested: "cuDNN"
   Try: "module spider cuDNN" to see how to load the module(s).



cuda:0
cuda:0
{'batch_size': 1024, 'alpha': 1.0, 'epochs': 100, 'patience': 20, 'expert_type': 'predict', 'n_classes': 10, 'k': 5, 'n_experts': 10, 'lr': 0.1, 'weight_decay': 0.0005, 'warmup_epochs': 0, 'loss_type': 'ova', 'ckp_dir': './ova_gradual_overlap/', 'experiment_name': 'gradual_overlap'}
Traceback (most recent call last):
  File "analyse_gradual_overlap.py", line 183, in <module>
    validation(model_name, expert_fns, config)
  File "analyse_gradual_overlap.py", line 113, in validation
    model.load_state_dict(torch.load(model_path, map_location=device))
  File "/home/rverma/.conda/envs/defer/lib/python3.8/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/rverma/.conda/envs/defer/lib/python3.8/site-packages/torch/serialization.py", line 231, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/rverma/.conda/envs/defer/lib/python3.8/site-packages/torch/serialization.py", line 212, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './ova_gradual_overlap/gradual_overlap_p_out_1.0_seed_948.pt'
srun: error: r28n5: task 0: Exited with exit code 1
